// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckFileStatus } from "./CheckFileStatus";

export type CheckFile = { path: string, base_path: string | null, status: CheckFileStatus, district: number | null, placed: boolean, };
