// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckEdge = { source: string, target: string, source_district: number, target_district: number, weight: number, static_import: boolean, };
