// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckThresholdSource } from "./CheckThresholdSource";

export type CheckThresholds = { max_districts: number | null, max_dq: number | null, source: CheckThresholdSource, };
