// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverageLanguage } from "./CoverageLanguage";
import type { ReferenceCoverage } from "./ReferenceCoverage";

export type CoverageReport = { zero_edge_files: number, total_files: number, by_language: { [key in string]: CoverageLanguage }, references?: { [key in string]: ReferenceCoverage } | null,
/**
 * Issue #115's guarded mirror rule ("Mirror rule, guarded"): the count
 * of TypeScript workspace-package import specifiers resolved, during
 * extraction, only by mapping an `exports`/`typesVersions` target
 * inside an absent build directory back to its source file
 * (`extract::mirror_build_output`) -- one import statement is one
 * unit, not a distinct file edge (two files importing the same mirror-
 * resolved specifier count as two). Counted separately so a guessed-
 * but-earned import stays distinguishable from a parsed one -- the
 * lower bound stays auditable. Zero on every map with no such
 * specifier (every map before this rule existed, and every repository
 * without this exact shape), so it is omitted rather than written as
 * `0`, keeping every such map byte-identical.
 */
build_output_mirror?: number, };
