// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverageLanguage } from "./CoverageLanguage";
import type { ReferenceCoverage } from "./ReferenceCoverage";

export type CoverageReport = { zero_edge_files: number, total_files: number, by_language: { [key in string]: CoverageLanguage }, references?: { [key in string]: ReferenceCoverage } | null,
/**
 * Issue #115's guarded mirror rule ("Mirror rule, guarded"): the count
 * of TypeScript workspace-package import specifiers resolved, during
 * extraction, only by mapping an `exports`/`typesVersions` target
 * inside an absent build directory back to its source file
 * (`extract::mirror_build_output`) -- one import statement is one
 * unit, not a distinct file edge (two files importing the same mirror-
 * resolved specifier count as two). Counted separately so a guessed-
 * but-earned import stays distinguishable from a parsed one -- the
 * lower bound stays auditable. Zero on every map with no such
 * specifier (every map before this rule existed, and every repository
 * without this exact shape), so it is omitted rather than written as
 * `0`, keeping every such map byte-identical.
 */
build_output_mirror?: number,
/**
 * Issue #162: Python import statements that resolved only through
 * the guarded cross-project fallback -- an absolute import no scope of
 * its own file resolves, taken into the one sibling project whose
 * module table owns its top-level package -- counted during the
 * extraction pass that makes those edges. The unit is import
 * statements, not file edges: a statement counts once however many
 * files it reaches, and one file importing a sibling in three
 * statements counts three. These edges rest on an inference (that the
 * sibling is installed), so they are counted apart to keep the lower
 * bound auditable. Zero on every map without such an import, and then
 * omitted rather than written as `0`, so every such map stays
 * byte-identical.
 */
python_cross_project?: number, };
