// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A district's legibility class -- see `geometry::classify_districts` for
 * how it's computed and `docs/FINDINGS.md`/issue #34 for the measurement
 * that motivated it. Lowercase on the wire (`#[serde(rename_all =
 * "lowercase")]`) to match every other string the map JSON hands the
 * viewer (`lang`, `names`'s values, landmark `why`/`detail`).
 */
export type DistrictClass = "mainland" | "island" | "unconnected";
