// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HierSymbolRow } from "./HierSymbolRow";
export type DistrictSymbols = { district: number, files: Array<number>, symbol_indices: Array<number>, symbols: Array<HierSymbolRow>, edges: Array<[number, number, number]>, module_code_lines: { [key in number]: number }, };
