// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DistrictClass } from "./DistrictClass";

export type District = { size: number, c: [number, number], blob: Array<Array<[number, number]>>, class: DistrictClass, };
