// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HierSymbolRow } from "./HierSymbolRow";
export type DistrictSymbols = { district: number, files: Array<number>, symbol_indices: Array<number>, symbols: Array<HierSymbolRow>, edges: Array<[number, number, number]>, module_code_lines: { [key in number]: number }, symbol_rings?: Array<Array<[number, number]> | null> | null, module_rings?: { [key in number]: Array<[number, number]> } | null, header_rings?: { [key in number]: Array<[number, number]> } | null, };
