// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EtaBasis } from "./EtaBasis";

export type Eta = { low_s: number, high_s: number, basis: EtaBasis, };
