// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerBuild } from "./WorkerBuild";

/**
 * `GET /api/healthz`'s body (docs/API.md). Additive since #97 phase 3:
 * `status` alone was the whole body before. `build` is this master's own
 * `hello.build` identity (docs/WORKER_TIER.md §3.6) -- what it insists a
 * worker's build matches before assigning it work, in local mode too
 * (`crate::service::workers::own_build` does not depend on
 * `TOLMAP_WORKERS`), so an operator can read it off a plain deployment
 * without a worker fleet at all.
 */
export type HealthzResponse = { status: string, build: WorkerBuild, };
