// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerBuild } from "./WorkerBuild";

export type HealthzResponse = { status: string, build: WorkerBuild, };
