// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Eta } from "./Eta";
import type { JobStatus } from "./JobStatus";
import type { ProgressValue } from "./ProgressValue";
import type { StageSnapshot } from "./StageSnapshot";

export type JobSnapshot = { job_id: string, slug: string, commit: string | null, status: JobStatus, stage: string, queue_position: number | null, started_at: string, finished_at: string | null, error: string | null, error_code: string | null, progress: ProgressValue | null, eta: Eta | null, eta_start_s: number | null, elapsed_s: number, stages: Array<StageSnapshot>, };
