// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobStatus = "queued" | "cloning" | "detecting" | "indexing" | "done" | "failed";
