// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Eta } from "./Eta";
import type { JobStatus } from "./JobStatus";
import type { ProgressValue } from "./ProgressValue";
import type { StageSnapshot } from "./StageSnapshot";

export type JobSnapshot = { job_id: string, slug: string, commit: string | null, status: JobStatus, stage: string, 
/**
 * One-based FIFO position while waiting; null once a worker starts.
 */
queue_position: number | null, started_at: string, finished_at: string | null, 
/**
 * Human-readable failure text, or null. Flat, not an object: this is
 * rendered directly by the client. The machine code lives beside it.
 */
error: string | null, 
/**
 * Machine-readable failure code (`cancelled`, `detection_failed`,
 * ...), or null. Clients branch on this rather than pattern-matching the
 * message text.
 */
error_code: string | null, progress: ProgressValue | null, eta: Eta | null, eta_start_s: number | null, elapsed_s: number, stages: Array<StageSnapshot>, 
/**
 * True while the job is active after its early map has been checked and
 * made available at its own commit (`GET /api/maps/{owner}/{repo}?commit=`).
 * The map has not passed the result checks yet. Cleared when the job is
 * done, failed, or re-queued; the viewer uses the registered map on
 * Done and keeps the job handover only while details are still pending.
 */
map_ready: boolean, };
