// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { District } from "./District";
import type { LandmarkRow } from "./LandmarkRow";
import type { NodeRow } from "./NodeRow";
import type { RoadRow } from "./RoadRow";
import type { SymbolRow } from "./SymbolRow";

export type MapDocument = { repo: string, q: number, names: { [key in string]: string }, districts: { [key in string]: District }, F: Array<string>, N: Array<NodeRow>, E: Array<[number, number]>, L: Array<LandmarkRow>, S: { [key in string]: Array<SymbolRow> }, U: { [key in string]: Array<number> }, roads: Array<RoadRow>, lang: string, P: { [key in string]: Array<[number, number]> } | null, };
