// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageId } from "./StageId";

export type ProgressValue = { stage: StageId, stage_index: number, stage_count: number, label: string, unit: string, done: bigint, total: bigint | null, rate_per_s: number | null, transfer_bytes?: bigint | null, transfer_rate_bytes_per_s?: number | null, };
