// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallCoverage } from "./InstallCoverage";

export type ReferenceCoverage = { path: string, reason: string, indexer: string | null, exit_code: number | null, files: number, files_indexed: number | null, hand_pairs: number, scip_pairs: number | null, recall: number | null, min_recall: number, granularity: string, install?: InstallCoverage | null, };
