// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageFeatures } from "./LanguageFeatures";

export type RepoFeatures = { clone_bytes: bigint | null, commits: bigint | null, languages: { [key in string]: LanguageFeatures }, refs?: string | null, install?: string | null, };
