// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StageId = "clone" | "clone_objects" | "clone_deltas" | "clone_checkout" | "detect" | "history" | "parse" | "resolve" | "blend_prune" | "partition" | "neighbourhoods" | "naming" | "regions" | "footprints" | "symbols" | "symbol_cards" | "write";
