// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageId } from "./StageId";
import type { StageState } from "./StageState";

export type StageSnapshot = { id: StageId, label: string, state: StageState, started_at: string | null, duration_s: number | null, };
