// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HierSymbolRow } from "./HierSymbolRow";
import type { SymbolCoverage } from "./SymbolCoverage";
export type SymbolsDocument = { files: Array<number>, symbols: Array<HierSymbolRow>, edges: Array<[number, number, number, number]>, kinds: Array<string>, module_code_lines: { [key in number]: number }, coverage: SymbolCoverage, symbol_rings?: Array<Array<Array<number>> | null> | null, module_rings?: { [key in number]: Array<Array<number>> } | null, header_rings?: { [key in number]: Array<Array<number>> } | null, };
