// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SymbolCoverage = { calls_total: number, calls_resolved: number, inherited_calls_resolved: number, possible_implementations: number, unresolved: { [key in string]: number }, };
