// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerrainArterial } from "./TerrainArterial";
import type { TerrainParcel } from "./TerrainParcel";
import type { TerrainSubdistrict } from "./TerrainSubdistrict";

export type TerrainDistrict = { arterials: Array<TerrainArterial>, subdistricts: Array<TerrainSubdistrict>, parcels: Array<TerrainParcel>, 
/**
 * Monotonic high-water mark; retired suffixes are never reissued.
 */
max_suffix: number, };
