// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerrainParcel = { address: string, members: Array<number>, 
/**
 * `[x, y, width, height]` in the same region coordinate system as `N`.
 */
rect: [number, number, number, number], };
