// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerrainArterial = { file: number, stranded: number, 
/**
 * Weighted-pruned in-district neighbours.  Keeping this separate from
 * `roads` matters: `RoadRow` joins top-level districts, while these
 * links draw one load-bearing file as a road inside its own district.
 */
links: Array<number>, };
