// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviousMap } from "./PreviousMap";

export type WorkerSpec = { v: number, slug: string, owner: string, repo: string, source: string, local: boolean, all_sources: boolean, cache_dir: string, output_dir: string, clone_cache_bytes: bigint, prune_variant: string, namer: string, namer_model: string, previous_maps: Array<PreviousMap>, names_cache: string | null, refs: string | null, install?: string | null, };
