// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artifact } from "./Artifact";
import type { ProgressValue } from "./ProgressValue";
import type { RepoFeatures } from "./RepoFeatures";
import type { StageId } from "./StageId";

export type WorkerEvent = { "type": "stage_started", v: number, stage: StageId, } | { "type": "progress", v: number, value: ProgressValue, } | { "type": "stage_finished", v: number, stage: StageId, duration_s: number, success: boolean, } | { "type": "features", v: number, features: RepoFeatures, } | { "type": "log", v: number, message: string, } | { "type": "result", v: number, map_path: string, symbols_path: string, symbols_dir: string, names_cache: string, commit: string, branch: string | null, lang: string, files: number, districts: number, modularity: number, artifacts?: Array<Artifact>, } | { "type": "error", v: number, code: string, message: string, } | { "type": "install_request", v: number, };
