// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `hello.build` (§3.2): identifies the exact build a worker runs, since a
 * different build or indexer version can produce a different map for the
 * same `(slug, commit)` (§3.6, "build identity is a scheduling
 * constraint"). The master only assigns jobs to agents whose `build`
 * matches its own.
 */
export type WorkerBuild = { version: string, commit: string, indexers: { [key in string]: string }, };
