// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviousMap } from "./PreviousMap";
export type WorkerSpec = { v: number, slug: string, owner: string, repo: string, source: string, local: boolean, cache_dir: string, output_dir: string, max_clone_bytes: number, max_history_commits: number, max_files: number, prune_variant: string, namer: string, namer_model: string, previous_maps: Array<PreviousMap>, names_cache: string | null, };
